runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/bol-mancala-ui/index.html
    upload: dist/bol-mancala-ui/index.html
  - url: /
    static_dir: dist/bol-mancala-ui

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
